[package]
name = "zip-http-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
hyper = { version = "0.14", features = ["http1", "server", "tcp"] }
log = "0.4"
mime_guess = "2"
simple_logger = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
zip = "0.5"
